// List of quotes to pick from for "summonQuote"
const quotes = [
    "Star searing flames of absolution!",
    "By my flesh and blood, be healed!",
    "Feel darkness blacker than midnight!",
    "Even when victory seems impossible… we march on!",
    "Aha! The weak spot!",
    "Oppose me and your destruction is inevitable!",
    "The head! Shoot him in the head!",
    "You have my gratitude.",
    "What doesn't kill you makes you stronger… apparently.",
    "Do not fret, I am with you!",
    "Rest assured that your issue will be attended to with haste!",
    "G-gotcha…friendio! Leave it to us…m-mate!",
    "Seeing you so happy… I know not why, but it makes me feel warm.",
    "Aizel, Hogard, Garan, Damil… I pray that you can see my efforts.",
    "Get your hands off me!",
    "See the future?! And you expect me to believe this rubbish?",
    "I thank you for your aid in my cause. Justice has been served.",
    "You are too kind.",
    "How dare you! You clown!",
    "I cannot speak now. But I shall fulfill my promise.",
    "If I am to lead the High Entia despite my mixed heritage... If I am to succeed the throne, then I accept what must be done.",
    "What trials await me, I wonder? I must not lose focus!",
    "I do not understand. But I do not suspect any falsehood in your words.",
    "I cannot walk outside as you see me now, so this garden gives me much relief.",
    "You're a funny one.",
    "I've seen this engraving around the capital. Many researchers have tried and failed to discover its meaning.",
    "Forefathers. I, your descendant Melia Antiqua, stand before you. For the sake of our world, release the seal!",
    "Don't say that! I don't care how improper it is. Let me cry.",
    "Do not mock me.",
    "If you do not grasp the importance of loved ones until after they are gone... That is simply too late.",
    "Gazing across our beloved land... It's a sight like no other. All those fears and worries just seem to melt away.",
    "What?! I cannot imagine Shulk being so...naughty!",
    "The truth is, when I was young, I fell from this very precipice. Ever since, I cannot bring myself to look over the edge.",
    "In love, it's hard to know when to hold back and when to act.",
    "Do you mean to say I am inflexible and stubborn? Is that it?! Although, now that you mention it...you're not exactly wrong.",
    "Is it unbecoming of me to dabble in such things?",
    "The sense of unity in our group means a great deal to me. I would not sacrifice it for anything.",
    "Is it not a crown princess' duty to collect monies owed to Alcamoth?",
    "Splish splash, flip flap?",
    "You've turned the gloomy cloud over my head into sunshine. Just being here with you is enough for me. Thank you.",
    "My fallen brethren, I promise to live my life to the fullest. Look over me as I journey on…",
    "What one sister has, the other craves. And we cannot have that!",
    "How can I be confident in myself?! I failed to save those close to me. I let them die... You think someone like that can rebuild an entire city?!",
    "Before, vengeance was all I could think of. But I realised it would lead to nothing good.",
    "I wish to build a world free of war, where no one must risk their lives.",
    "I dress...differently to other girls?",
    "If you keep talking like that, you'll get back in my good books. But I do wonder what it would be like if I were not a princess...",
    "I shall take your advice into consideration. And maybe one day you will see me do something...crazy.",
    "Flowers are transient, so it is hard to get attached to them. As with soldiers in battle, death is always knocking.",
    "I think I know the perfect flower for you. The renowned Stardrop! None can deny its beauty. All other flowers bow down and wilt at its magnificence.",
    "I can always see a person's true nature from how they act in public. I've studied you all ever since we met.",
    "Enough of this conversation! You are not second, third or fourth. You are last!",
    "I have already lived for a great number of years. But never before have I experienced these emotions.",
    "Yet I feel...strangely relieved. As if I can move on with my life and forget this pain in my heart.",
    "My father and brother's expectations... Calling me 'the Hope of the High Entia'... I must be an empress worthy of taking on that mantle, but I don't know how...",
    "Wha- I hardly think I said anything funny!",
    "…Hahah. My gloom is no match for you.",
    "I can hear Father lecturing me even now, chiding me for my foolishness.",
    "For the sake of all the people of this world, that they may decide the future as equals. That is the vision I choose to guide me. That is the future I wish for.",
    "How can I explain this...? Tyrea and I have separate parents. Different fathers and different mothers, both.",
    "…Play-play?",
    "Can it really be your intention to keep blaming yourself?! Why?! Why won't you turn your eyes to the future?! Is this what your mother would have wanted?",
    "I, Melia Antiqua, Empress of the High Entia, by mine name do solemnly decree: Be thou guardian, for our subjects and the race entire. Act the mistress of unseen shadows, and pledge thy very life to this throne. Swear your might... to my bidding, Tyrea.",
    "I hardly think you need to feel hurried. This journey we're on is a certain first step on the way to achieving your dream. I know you will have many chances to prove yourself yet.",
    "What really counts is inside you. But you still have much time. Perhaps it would do you good to think on it awhile.",
    "Well, being told the answers does not equal learning. How about this... Why don't we think on it together?",
    "Father... Brother... With these two hands of mine, I will reclaim Alcamoth!",
    "I have an ill premonition. Disaster... Complete ruin, inescapably looming over our future.  I know not why... but that is the vague dread that I feel when I consider the rift.",
    "The future is ours, and it is decided here. All we can do is give our all to build a better one.",
    "Enough. I'll hear no more of this self-loathing!",
    "What's more, Tyrea... You're all the family I have left..."
];

module.exports = { quotes };